### Word Embedding Techniques using Embedding Layer in Keras

In [ ]:
### Libraries USed Tensorflow> 2.0  and keras

In [ ]:
# !pip install tensorflow-gpu

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.18.0


In [ ]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [ ]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [ ]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [ ]:
### Vocabulary size
voc_size=500

#### One Hot Representation

In [ ]:
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[471, 162, 296, 366], [471, 162, 296, 434], [471, 166, 296, 49], [61, 86, 7, 244, 109], [61, 86, 7, 244, 361], [85, 471, 213, 296, 318], [309, 317, 217, 244]]


### Word Embedding Represntation

In [ ]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [ ]:
import numpy as np

In [ ]:
## pre padding
sent_length=10
embedded_docs=np.array(pad_sequences(onehot_repr,padding='pre',maxlen=sent_length))
print(embedded_docs)

[[  0   0   0   0   0   0 471 162 296 366]
 [  0   0   0   0   0   0 471 162 296 434]
 [  0   0   0   0   0   0 471 166 296  49]
 [  0   0   0   0   0  61  86   7 244 109]
 [  0   0   0   0   0  61  86   7 244 361]
 [  0   0   0   0   0  85 471 213 296 318]
 [  0   0   0   0   0   0 309 317 217 244]]


In [ ]:
## 10 feature dimesnions
dim=10


In [ ]:
model=Sequential()
model.add(Embedding(input_dim=voc_size, output_dim=10,input_shape=(sent_length,)))
model.compile('adam','mse')

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [ ]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 10, 10)         │         5,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 5,000 (19.53 KB)

 Trainable params: 5,000 (19.53 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
print(model.predict(embedded_docs))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 234ms/step
[[[-0.00487778  0.04274413 -0.02806186  0.0013788   0.0465205
   -0.03232276 -0.04625181  0.02153077  0.03517646  0.02721092]
  [-0.00487778  0.04274413 -0.02806186  0.0013788   0.0465205
   -0.03232276 -0.04625181  0.02153077  0.03517646  0.02721092]
  [-0.00487778  0.04274413 -0.02806186  0.0013788   0.0465205
   -0.03232276 -0.04625181  0.02153077  0.03517646  0.02721092]
  [-0.00487778  0.04274413 -0.02806186  0.0013788   0.0465205
   -0.03232276 -0.04625181  0.02153077  0.03517646  0.02721092]
  [-0.00487778  0.04274413 -0.02806186  0.0013788   0.0465205
   -0.03232276 -0.04625181  0.02153077  0.03517646  0.02721092]
  [-0.00487778  0.04274413 -0.02806186  0.0013788   0.0465205
   -0.03232276 -0.04625181  0.02153077  0.03517646  0.02721092]
  [ 0.01223816 -0.03324882 -0.02669412 -0.03066315 -0.01883437
   -0.02697935  0.01888764 -0.00659999 -0.04821367 -0.02549146]
  [-0.02458049 -0.03012533 -0.01252477  0.01260639  0.00830016
   -0.02349334 

In [ ]:
##'the glass of milk',
embedded_docs[0]

array([  0,   0,   0,   0,   0,   0, 471, 162, 296, 366], dtype=int32)

In [ ]:
print(model.predict(embedded_docs)[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
[[-0.00487778  0.04274413 -0.02806186  0.0013788   0.0465205  -0.03232276
  -0.04625181  0.02153077  0.03517646  0.02721092]
 [-0.00487778  0.04274413 -0.02806186  0.0013788   0.0465205  -0.03232276
  -0.04625181  0.02153077  0.03517646  0.02721092]
 [-0.00487778  0.04274413 -0.02806186  0.0013788   0.0465205  -0.03232276
  -0.04625181  0.02153077  0.03517646  0.02721092]
 [-0.00487778  0.04274413 -0.02806186  0.0013788   0.0465205  -0.03232276
  -0.04625181  0.02153077  0.03517646  0.02721092]
 [-0.00487778  0.04274413 -0.02806186  0.0013788   0.0465205  -0.03232276
  -0.04625181  0.02153077  0.03517646  0.02721092]
 [-0.00487778  0.04274413 -0.02806186  0.0013788   0.0465205  -0.03232276
  -0.04625181  0.02153077  0.03517646  0.02721092]
 [ 0.01223816 -0.03324882 -0.02669412 -0.03066315 -0.01883437 -0.02697935
   0.01888764 -0.00659999 -0.04821367 -0.02549146]
 [-0.02458049 -0.03012533 -0.01252477  0.01260639  0.00830016 -0.02349334
  -0.00896164

In [ ]:
### Assignment

sent=["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"
      ]